services:
  site:
    image: rickensptech/rickenaerocontrol:node
    ports:
      - "3333:3333"
    networks:
      - rede-compose
    depends_on:
      - db
  db:
    image: rickensptech/rickenaerocontrol:mysql
    ports:
      - "3306:3306"
    networks:
      - rede-compose
networks:
  rede-compose:
    driver: bridge