services:
  site:
<<<<<<< HEAD
    image: arthurrocha/aerocontrol:node
=======
    image: rickensptech/rickenaerocontrol:node
>>>>>>> 83a33b13cb57fd3131d09ad794bbecab7b2949bd
    ports:
      - "3333:3333"
    networks:
      - rede-compose
    depends_on:
      - db
  db:
    image: rickensptech/rickenaerocontrol:mysql
    ports:
      - "3306:3306"
    networks:
      - rede-compose
networks:
  rede-compose:
    driver: bridge